compiler:
    # evm_version: null
    solc:
        # version: null
        optimizer:
            enabled: false
            # enabled: true
            # runs: 200
        remappings: null

# need dotenv
dotenv: .env

networks:
    Ropsten:
        chainid: 3
        id: ropsten
        host: https://mainnet.infura.io/v3/${WEB3_INFURA_PROJECT_ID}
        explorer: https://api-ropsten.etherscan.io/api

wallets:
    from_key: ${PRIVATE_KEY}
